version: "3"
services:
  mysqlsrv:
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bm_store_dev"
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
