// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "API Documentation Test",
    "version": "1"
  },
  "paths": {
    "/hello": {
      "post": {
        "summary": "hello",
        "description": "",
        "operationId": "hello.post.hello",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/create-customer": {
      "post": {
        "summary": "createCustomer",
        "description": "",
        "operationId": "createCustomer.post.create-customer",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "PostBodyHello": {
      "properties": {
        "status": {
          "title": "PostBodyHello.status",
          "type": "string"
        },
        "message": {
          "title": "PostBodyHello.message",
          "type": "string"
        },
        "isOk": {
          "title": "PostBodyHello.isOk",
          "type": "boolean"
        }
      },
      "required": [
        "status",
        "message",
        "isOk"
      ],
      "additionalProperties": false,
      "title": "PostBodyHello",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http",
    "https"
  ]
};