name: Deploy Backend Hom

on:
  push:
    branches:
      - homologation

jobs:
  DeployHomologation:
    name: Build and Deploy Homologation 🚀
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:  npm ci --quiet
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless deploy --region us-east-1 --stage hom"
          entrypoint: /bin/sh
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_DATABASE: ${{secrets.DB_DATABASE}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_HOST: ${{secrets.DB_HOST}}
